services:
  node:
    image: node
    user: node
    working_dir: /home/node
    command: tail -f /dev/null
    ports:
      - ${NODE_START_PORT:-3000}-${NODE_END_PORT:-3009}:3000-3009
    volumes:
      - ../apeframework:/home/node/apeframework
      - ../apeframework-eslint:/home/node/apeframework-eslint
